require("xenophon.lazy")
require("xenophon.telescope")
require("xenophon.leap")
require("xenophon.neotree")
require("xenophon.toggleterm")
require("xenophon.smartsplitter")
require("xenophon.indent")
require("xenophon.lualine")
require("xenophon.mini")
require("xenophon.notify")
require("xenophon.flit")
require("xenophon.css")
require("xenophon.dap_ui")
require("xenophon.dap")
require("xenophon.global")
require("xenophon.bufferline")
require("xenophon.mini-ai")
require("xenophon.godot")
require("xenophon.copilot")
require("xenophon.settings")
require("xenophon.theme-global")
require("xenophon.theme-tokyonight")
-- require("xenophon.theme-kanagawa")
-- require("xenophon.theme-monokai")
-- require("xenophon.theme-onedark")
-- require("xenophon.theme-github")
